### ISSUE TITLE
weird looking when using shell themes

### ISSUE THREAD

**Issue by luizkowalski** [zacbarton/gnome-shell-extension-bolt#16]
this is how bolt looks like when I set a shell theme (ElementaryOS shell theme, from AUR, beign more specifically).

![Bolt](http://i.imgur.com/4hDsp.png)

any ideas?

**Comment by zacbarton** [comment]
can you provide a link to the theme download?

**Comment by luizkowalski** [comment]
As I'm using Arch Linux, I've downloaded via yaourt
this is the package: http://aur.archlinux.org/packages.php?ID=53070
the package says the theme is here: http://www.deviantart.com/download/262479724/gnome_shell__eos_by_0rax0-d4c9ung.zip

**Comment by zacbarton** [comment]
Thanks for the info. I worked with the eOS author when creating bolt and unfortunately the theme hasnt been updated to work with the latest version of bolt. You can download an updated (although unofficial) theme from below.

http://zacbarton.com/temp/eOS-bolt.tar.gz

**Comment by 0rAX0** [comment]
@luizkowalski So sorry about the problem, I'm a little bit busy these days. Please use the version provided by @zacbarton until I update the theme to use the new classes.

Also, you can optionally open the gnome-shell.css file and comment out the parts that style Bolt, at the bottom of the file.

**Comment by luizkowalski** [comment]
@0rAX0 that's ok :) we're all busy these days hahaha :)
@zacbarton thanks for your link, bolt is working much better now :D
