### ISSUE TITLE
Bolt hang system up to 20-30 seconds on first search

### ISSUE THREAD

**Issue by ambercloud** [zacbarton/gnome-shell-extension-bolt#2]
When I open Bolt for a first time after login it takes up to 20-30 seconds to open. And whole gnome-shell hangs until bolt opens. It happens also when you change from "home" screen to "files" first time.

I'm using Ubuntu 12.04. Please, feel free to ask for any additional information.

**Comment by zacbarton** [comment]
Hopefully the next version will improve this somewhat.
