### ISSUE TITLE
Any chance we are going to get updated?

### ISSUE THREAD

**Issue by Goddard** [zacbarton/gnome-shell-extension-bolt#22]
I was just curious if we were gonna get this updated for the newer gnome versions?

**Comment by zacbarton** [comment]
Yes I intend to. Finding spare time is a little tough right now though.

**Comment by Goddard** [comment]
Anything I can do to help?

**Comment by zacbarton** [comment]
I've just submitted a version to the extensions website that works with 3.6

**Comment by Goddard** [comment]
Awesome.. thank you sir.

**Comment by pyaazkaparatha** [comment]
Will it get updated for 3.16?

**Comment by zacbarton** [comment]
I'm afraid not @pyaazkaparatha :-(
